// <auto-generated />
using FullStack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullStack.Data.Migrations
{
    [DbContext(typeof(FullStackDbContext))]
    [Migration("20211022074709_PriceIntervals")]
    partial class PriceIntervals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullStack.Data.Entities.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdvertDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdvertHead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdvertState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("FullStack.Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Johannesburg",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pretoria",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bloemfontein",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Welkom",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cape Town",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Stellenbosch",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Durban",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Petermaritzburg",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Polokwane",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "Modimolle",
                            ProvinceId = 5
                        });
                });

            modelBuilder.Entity("FullStack.Data.Entities.PriceInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PriceIntervalDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceIntervalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PriceIntervals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PriceIntervalDisplay = "R10,000 - R4,999,999",
                            PriceIntervalValue = 10000m
                        },
                        new
                        {
                            Id = 2,
                            PriceIntervalDisplay = "R5,000,000 - R9,999,999",
                            PriceIntervalValue = 5000000m
                        },
                        new
                        {
                            Id = 3,
                            PriceIntervalDisplay = "R10,000,000 - R14,999,999",
                            PriceIntervalValue = 10000000m
                        },
                        new
                        {
                            Id = 4,
                            PriceIntervalDisplay = "R15,000,000 - R19,999,999",
                            PriceIntervalValue = 15000000m
                        },
                        new
                        {
                            Id = 5,
                            PriceIntervalDisplay = "R20,000,000 - R24,999,999",
                            PriceIntervalValue = 20000000m
                        },
                        new
                        {
                            Id = 6,
                            PriceIntervalDisplay = "R25,000,000 - R29,999,999",
                            PriceIntervalValue = 25000000m
                        },
                        new
                        {
                            Id = 7,
                            PriceIntervalDisplay = "R30,000,000 - R34,999,999",
                            PriceIntervalValue = 30000000m
                        },
                        new
                        {
                            Id = 8,
                            PriceIntervalDisplay = "R35,000,000 - R39,999,999",
                            PriceIntervalValue = 35000000m
                        },
                        new
                        {
                            Id = 9,
                            PriceIntervalDisplay = "R40,000,000 - R44,999,999",
                            PriceIntervalValue = 40000000m
                        },
                        new
                        {
                            Id = 10,
                            PriceIntervalDisplay = "R45,000,000 - R49,999,999",
                            PriceIntervalValue = 45000000m
                        },
                        new
                        {
                            Id = 11,
                            PriceIntervalDisplay = "R50,000,000 - R54,999,999",
                            PriceIntervalValue = 50000000m
                        },
                        new
                        {
                            Id = 12,
                            PriceIntervalDisplay = "R55,000,000 - R59,999,999",
                            PriceIntervalValue = 55000000m
                        },
                        new
                        {
                            Id = 13,
                            PriceIntervalDisplay = "R60,000,000 - R64,999,999",
                            PriceIntervalValue = 60000000m
                        },
                        new
                        {
                            Id = 14,
                            PriceIntervalDisplay = "R65,000,000 - R69,999,999",
                            PriceIntervalValue = 65000000m
                        },
                        new
                        {
                            Id = 15,
                            PriceIntervalDisplay = "R70,000,000 - R74,999,999",
                            PriceIntervalValue = 70000000m
                        },
                        new
                        {
                            Id = 16,
                            PriceIntervalDisplay = "R75,000,000 - R79,999,999",
                            PriceIntervalValue = 75000000m
                        },
                        new
                        {
                            Id = 17,
                            PriceIntervalDisplay = "R80,000,000 - R84,999,999",
                            PriceIntervalValue = 80000000m
                        },
                        new
                        {
                            Id = 18,
                            PriceIntervalDisplay = "R85,000,000 - R89,999,999",
                            PriceIntervalValue = 85000000m
                        },
                        new
                        {
                            Id = 19,
                            PriceIntervalDisplay = "R90,000,000 - R94,999,999",
                            PriceIntervalValue = 90000000m
                        },
                        new
                        {
                            Id = 20,
                            PriceIntervalDisplay = "R95,000,000 - R100,000,000",
                            PriceIntervalValue = 95000000m
                        });
                });

            modelBuilder.Entity("FullStack.Data.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gauteng"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Free State"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Western Cape"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kwazulu-Natal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Limpopo"
                        });
                });

            modelBuilder.Entity("FullStack.Data.Entities.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("FullStack.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Bernard",
                            LastName = "Strauss",
                            Password = "Bernard123",
                            Role = "Admin",
                            Username = "bernards@welcomehome.co.za"
                        });
                });

            modelBuilder.Entity("FullStack.Data.Entities.Advert", b =>
                {
                    b.HasOne("FullStack.Data.Entities.User", "User")
                        .WithMany("Adverts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FullStack.Data.Entities.City", b =>
                {
                    b.HasOne("FullStack.Data.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FullStack.Data.Entities.Seller", b =>
                {
                    b.HasOne("FullStack.Data.Entities.User", null)
                        .WithOne("Seller")
                        .HasForeignKey("FullStack.Data.Entities.Seller", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
